### ISSUE TITLE
Incorrect path separators

### ISSUE THREAD

**Issue by netrikare** [GabrielBB/vscode-lombok#1]
Current path separators prevent to run the extension on Linux.
in package.json, section "lombokConfig" -  changing this:
`
        "path": "\\server\\lombok.jar",
`
to this:
`
        "path": "/server/lombok.jar",
`
solves the issue for me.

**Comment by GabrielBB** [comment]
Hi, @netrikare . Thanks for the feedback. Since you found the problem and also provided a solution, which i already tested with a Linux and a Mac computer. Can you, please, make a pull request so in your github shows that you contributed to this project?

**Comment by GabrielBB** [comment]
@netrikare Thanks for the feedback. Tested and published
