### ISSUE TITLE
not work ,when f5  err appear,  when open the java file,the err disappear

### ISSUE THREAD

**Issue by ladixiu** [GabrielBB/vscode-lombok#12]
confuesed

**Comment by GabrielBB** [comment]
Are you using Maven or Gradle? Did you add Lombok dependency?

**Comment by ladixiu** [comment]
using mave and lombok dependency added
the project is original in idea
i am very like vs code and try to use
then the err appear

very odd，when i open the err java file, the err disappear
whe i use f5 to debug，err appear


sorry,forgive my poor en

**Comment by ladixiu** [comment]
in idea is ok

**Comment by ladixiu** [comment]
via mvn package is ok

**Comment by ladixiu** [comment]
i guess the proplom is the java debug plugins，
i just go to java dubug qa
