### ISSUE TITLE
Problems list still show errors of undefined for getters or setters

### ISSUE THREAD

**Issue by maknowledge** [GabrielBB/vscode-lombok#13]
lombok is working correctly when running application but problems list still show errors of undefined setters or getters.
they wont be refreshed automatically.
After clicked the messages of errors manually, the messages disappear.

**Comment by maknowledge** [comment]
after clean off my project, made new project again and loaded on vscode, all of things well done.
thanks.

**Comment by jcjolley** [comment]
Despite restarting vscode, running mvn clean and mvn install, and repeating this process several times, I am still getting "The method get<PROPNAME>() is undefined for the type <CLASS>" on all of my @Data classes.

Any guidance?

**Comment by GabrielBB** [comment]
@jcjolley Is your project on some git repo that I can check out and test or is a private project ?

**Comment by jcjolley** [comment]
Sadly, it's a work project. Tomorrow I can try to get a public repro project together for you (or just prove that it works, one of the two :D)

**Comment by unguiculus** [comment]
I'm having the same problem. I get hundreds of errors which only disappear when the affected files are opened. It's a Spring Boot Maven project. This is the list of Java-related extensions I use:

```
GabrielBB.vscode-lombok
k--kato.intellij-idea-keybindings
Pivotal.vscode-spring-boot
redhat.java
redhat.vscode-xml
redhat.vscode-yaml
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscjava.vscode-spring-boot-dashboard
```

**Comment by GabrielBB** [comment]
There is an open issue to the VSCode Java Extension with this same problem: [False positives problems (when using Lombok)](https://github.com/redhat-developer/vscode-java/issues/458). I will reference this issue there so they know that this problem is still happening

**Comment by rikoe** [comment]
Related to this issue: https://github.com/redhat-developer/vscode-java/issues/580

**Comment by TarjanSahu** [comment]
hey any one know how to resolve this issue on sts-4(ide)
