### ISSUE TITLE
Keep the classes generated when VSCode it's closing and reopen

### ISSUE THREAD

**Issue by credondocr** [GabrielBB/vscode-lombok#14]
As per user I want to keep all the time the classes generated with lombok.

My issue is each time when I close and reopen the VS Code I need to open again all classes in order to generate classes again.

That behavior is really odd, maybe I did something wrong.

Thanks

**Comment by GabrielBB** [comment]
Can you attach a sample project? That behavior is not normal

**Comment by credondocr** [comment]
Unfortunately I can't but seems is a isolated problem from my environment, thanks
