### ISSUE TITLE
Uninstall vscode-lombok on Windows 10 doesn't revert the changes made on the user settings

### ISSUE THREAD

**Issue by yaohaizh** [GabrielBB/vscode-lombok#15]
Platform: 

> Version: 1.31.0 (user setup)
> Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
> Date: 2019-02-05T22:35:56.624Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17763

Repro steps: 
1. Install vscode-lombok and the user settings is chanaged with lombok jar package.
2. Uninstall vscode-lombok

Expected: 
The added lombok.jar will be reverted from the user settings. 

Actually: 
The user settings is untouched, which cause the language server crashed.

**Comment by GabrielBB** [comment]
Fixed in vscode-lombok 1.0.0 (VSCode full restart is required after uninstalling extension)
