### ISSUE TITLE
Problem reported when i reopen the project

### ISSUE THREAD

**Issue by lvhuat** [GabrielBB/vscode-lombok#16]
Maybe i use in wrong way,every time i open the project,there is a large number of errors in output problem.
But when i open the file,the problem disappeared.

Which the most problems is look like:
```
the constructor xxx is undefined
xxx cannot be resolved
```

**Comment by rafbermudez** [comment]
I'm having this problem too. Any idea to solve it?

**Comment by rafbermudez** [comment]
I solved this problem:

I use lombok-1.16.22.jar in my project, but the plugin are using lombok-1.18.4 in server/lombok.jar. If I upgrade my version (or replace the jar plugin version) the problem dissapears.

Another solution would be changing the "java.jdt.ls.vmargs" in settings.json

**Comment by GabrielBB** [comment]
Update VSCode extension and make sure to use the latest Lombok dependency on your Pom.xml or build.gradle
