### ISSUE TITLE
Duplicate method for usage of multile annotations

### ISSUE THREAD

**Issue by masterofeye** [GabrielBB/vscode-lombok#19]
Hello,

I have the problem that VS Code marks all the combination of @RequiredArgsConstructor and @NoArgsConstructor with the error: "Duplicate method XXX() in Type XXX

VS Version: 1.31
Java Extension Pack
Spring Boot Extention Pack
Lombok

Here is a example:

`package de.schleissheimer.remoteview.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import io.micrometer.core.lang.NonNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

@entity
@table(name="company")
@DaTa
@RequiredArgsConstructor
@NoArgsConstructor
@builder
public class Company {

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name ="idCompany")
@NonNull
private Long id;

@NonNull
private String name;

}`

**Comment by GabrielBB** [comment]
@Data already provides the features of @RequiredArgConstructor (Check documentation). Can you try removing @RequiredArgConstructor since it is not necessary and maybe it is really creating duplicate code

**Comment by masterofeye** [comment]
I need to user @lombok.NonNull and not @NonNull ...

**Comment by GabrielBB** [comment]
Did you solve the problem, then?
