### ISSUE TITLE
SetterPrefix is not supported

### ISSUE THREAD

**Issue by SharathAnurag** [GabrielBB/vscode-lombok#31]
I am able to add seeterPrefix to @builder with setterPrefix = "with". But lombok is not able to generate that method in builder.

**Comment by GabrielBB** [comment]
@SharathAnurag Which Lombok version is your project using?

**Comment by GabrielBB** [comment]
@SharathAnurag Okay, I see the problem. I will try to publish the solution as soon as possible

**Comment by GabrielBB** [comment]
@SharathAnurag Please, update the extensión, restart vscode and try again

**Comment by SharathAnurag** [comment]
It's working thanks
