### ISSUE TITLE
lombook extension is not in effect

### ISSUE THREAD

**Issue by alwaysRemember** [GabrielBB/vscode-lombok#35]
- vscode version : 1.43.0
- vscode-lombok version: 1.0.1;
![image](https://user-images.githubusercontent.com/26773809/76394989-5a166600-63b1-11ea-84cc-0325d1de039f.png)
![image](https://user-images.githubusercontent.com/26773809/76395033-6ef2f980-63b1-11ea-8e92-6eec2a917a5a.png)

**Comment by GabrielBB** [comment]
Which Lombok version are you using in your Pom.xml or gradle file ? Please, try with the latest version

**Comment by alwaysRemember** [comment]
My lombok version is 1.18.12

**Comment by alwaysRemember** [comment]
Java and maven path configuration is also no problem. @GabrielBB

**Comment by GabrielBB** [comment]
@alwaysRemember which java version?

**Comment by alwaysRemember** [comment]
1.8





------------------ Original ------------------

**Comment by alwaysRemember** [comment]
java version : 1.8.0_191
maven version: 3.5.0
OS name: "mac os x",
version: "10.14.5", 
arch: "x86_64",
family: "mac" @GabrielBB
