### ISSUE TITLE
Support @Sl4j annotation

### ISSUE THREAD

**Issue by thiago-souza** [GabrielBB/vscode-lombok#4]
It would be awesome.
https://projectlombok.org/api/lombok/extern/slf4j/Slf4j.html

**Comment by kpb** [comment]
+1
We use this annotation in all our projects!

**Comment by denierlexiese** [comment]
+1
 I would love it. Thanks!!!

**Comment by lemonti** [comment]
+1

**Comment by colaicecream** [comment]
+1
Thanks!

**Comment by GabrielBB** [comment]
Tested with Gradle 5.4.1 and Java 8. This are my dependencies:

```
compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.26'
compile group: 'ch.qos.logback', name:'logback-classic', version: '1.2.3'
compile group: 'ch.qos.logback', name:'logback-core', version: '1.2.3'
```
Result:

![image](https://user-images.githubusercontent.com/8752823/57183346-94ea6c00-6e79-11e9-8055-52a3f4f75cce.png)

I will be updating the README.md with the @Sl4j annotation support
