### ISSUE TITLE
Error: Could not find or load main class Spring.Boot JDK10

### ISSUE THREAD

**Issue by ait0z** [GabrielBB/vscode-lombok#5]
I've been having issues debugging applications when the Lombok plugin is enabled (it throws a ClassNotFoundException). 
```
Error: Could not find or load main class com.tangoe.con.migrationserver.MigrationServer
Caused by: java.lang.ClassNotFoundException: com.tangoe.con.migrationserver.MigrationServer
```

When I uninstall the plugin I can again debug through the java debugger.
I'm using JDK 10 with a spring.boot application. My debug configuration in launch.json is the default that was generated (and worked prior to installing this plugin):
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [{
        "type": "java",
        "name": "Debug (Launch)-MigrationServer<migrationserver>",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "console": "internalConsole",
        "stopOnEntry": false,
        "mainClass": "com.tangoe.con.migrationserver.MigrationServer",
        "projectName": "migrationserver",
        "args": ""
    }]
```
I have not configured Lombok in any way and use the typical Microsoft Java Extension Pack and Red Hat language support for Java (which might've come with it).

I'm running VS Code on a MacBook (High-Sierra 10.13.6) with:
```
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
```
I believe I installed the JDK through homebrew and use jenv (have multiple JDKs but its all set to the above now).

**Comment by mynamezhulei** [comment]
JDK11 has the same question，and when I unstall this plugin and remove user setting.json where java.jdt.ls.vmargs ，It's OK to  run a spring boot app

**Comment by vk011** [comment]
Guys have you found the solution to this? I have the same problem with spring boot and jdk 11.

**Comment by rikoe** [comment]
I just found the same issue, this thread fixes it: https://github.com/redhat-developer/vscode-java/issues/580

**Comment by GabrielBB** [comment]
Fixed. Update the plugin in your VSCode and make sure you have the latest Lombok dependency on your Pom.xml / build.gradle

**Comment by GabrielBB** [comment]
Closing issue
