### ISSUE TITLE
Having undefined when using @Data 

### ISSUE THREAD

**Issue by AoftionStyle** [GabrielBB/vscode-lombok#67]
![data undefined](https://user-images.githubusercontent.com/25454399/156410775-e1e7e6f9-005b-4003-a179-1d8fe589962d.jpg)

Environment
OS: macOS Monterey 12.2.1
JDK version: openjdk 11.0.12 2021-07-20
Visual Studio Code Version: 1.64.2
Lombok Annotations Support for VS Code:v1.0.1

![image](https://user-images.githubusercontent.com/25454399/156411671-68614e74-2e7b-452f-ac4f-44ad2595a420.png)

**Comment by louisdefromont** [comment]
> This Issue closed, I just found setting.json have to contain this "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:"/Users/aoftion/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar""

What did you do the fix the issue? I have the same issue and I see the setting.json with the same config as you but I don't know what to do

**Comment by AoftionStyle** [comment]
> What did you do the fix the issue? I have the same issue and I see the settings.json with the same config as you but I don't know what to do

Need to add -javaagent:\"/Users/.vscode/extensions/gabrielbb.vscode-lombok-1.0.1/server/lombok.jar\" into your editor profile
